import { Category, EssentialPreset, PartnerPreset, Transaction } from '../types';

export const CATEGORIES: Category[] = [
  { id: 'food', name: 'Food & Dining', icon: 'UtensilsCrossed', color: '#00E55F', budget: 4000 },
  { id: 'hall', name: 'Hall Dining', icon: 'Soup', color: '#F5A623', budget: 2500 },
  { id: 'transport', name: 'Transport', icon: 'Bus', color: '#4C8DFF', budget: 1500 },
  { id: 'printout', name: 'Printout & Stationery', icon: 'FileText', color: '#D69E2E', budget: 600 },
  { id: 'recharge', name: 'Mobile Recharge & Data', icon: 'Smartphone', color: '#8B7FF5', budget: 800 },
  { id: 'banking', name: 'Banking & Send Money', icon: 'CreditCard', color: '#14B8A6', budget: 500 },
  { id: 'tea', name: 'Tea & Snacks', icon: 'Coffee', color: '#DD6B20', budget: 1200 },
  { id: 'books', name: 'Books & Study Material', icon: 'BookOpen', color: '#3B9EFF', budget: 1500 },
  { id: 'sports', name: 'Sports & Recreation', icon: 'Dumbbell', color: '#22C55E', budget: 800 },
  { id: 'clothing', name: 'Clothing & Laundry', icon: 'Shirt', color: '#EF4444', budget: 1500 },
  { id: 'health', name: 'Medicine & Health', icon: 'Pill', color: '#EF4444', budget: 800 },
  { id: 'events', name: 'Events & Outings', icon: 'Ticket', color: '#D69E2E', budget: 1200 },
  { id: 'essentials', name: 'Daily Essentials', icon: 'ShoppingBag', color: '#71717A', budget: 1000 },
  { id: 'partner', name: 'Partner & Outings', icon: 'Heart', color: '#E85D8A', budget: 3000 },
  { id: 'gaming', name: 'Gaming & Activity P/L', icon: 'Dices', color: '#3B9EFF', budget: 1000 },
  { id: 'rent', name: 'Room Rent & Utilities', icon: 'Home', color: '#4C51BF', budget: 5000 },
  { id: 'misc', name: 'Miscellaneous', icon: 'Package', color: '#71717A', budget: 1000 },
];

export const ESSENTIAL_PRESETS: EssentialPreset[] = [
  { id: '1', name: 'Benson & Hedges', price: 23, category: 'essentials' },
  { id: '2', name: 'Gold Leaf', price: 18, category: 'essentials' },
  { id: '3', name: 'Marlboro Light', price: 23, category: 'essentials' },
  { id: '4', name: 'Lucky Strike', price: 12, category: 'essentials' },
  { id: '5', name: 'Dunhill Switch', price: 25, category: 'essentials' },
  { id: '6', name: 'Star Filter', price: 10, category: 'essentials' },
  { id: '7', name: 'Hot Milk Tea', price: 15, category: 'tea' },
  { id: '8', name: 'Espresso Coffee', price: 40, category: 'tea' },
];

export const PARTNER_PRESETS: PartnerPreset[] = [
  { id: 'p1', name: 'Ice Cream Treat', price: 180, icon: 'IceCream' },
  { id: 'p2', name: 'Restaurant Dinner', price: 850, icon: 'UtensilsCrossed' },
  { id: 'p3', name: 'Weekend Hangout', price: 450, icon: 'Popcorn' },
  { id: 'p4', name: 'Tour / Outing Fund', price: 1500, icon: 'Palmtree' },
  { id: 'p5', name: 'Surprise Flowers', price: 250, icon: 'Flower2' },
  { id: 'p6', name: 'Special Cafe Coffee', price: 120, icon: 'Coffee' },
];

export const INCOME_SOURCES = [
  'Monthly Allowance',
  'Tuition / Part-time Job',
  'bKash / Bank Transfer',
  'Scholarship',
  'Freelancing',
  'Sold Item',
  'Other Income',
];

export const SEED_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    type: 'income',
    desc: 'Monthly Allowance from Home',
    source: 'Monthly Allowance',
    amount: 15000,
    date: new Date().toISOString().split('T')[0],
    note: 'Sent via bKash',
  },
  {
    id: 'tx-2',
    type: 'income',
    desc: 'Private Tuition Salary',
    source: 'Tuition / Part-time Job',
    amount: 6000,
    date: new Date(Date.now() - 86400000 * 2).toISOString().split('T')[0],
    note: 'Physics Batch 12',
  },
  {
    id: 'tx-3',
    type: 'expense',
    desc: 'Hall Khichuri & Meal Token',
    category: 'hall',
    amount: 220,
    date: new Date().toISOString().split('T')[0],
    note: 'Lunch at Hall Dining',
  },
  {
    id: 'tx-4',
    type: 'expense',
    desc: 'CNG Fare to Campus',
    category: 'transport',
    amount: 180,
    date: new Date().toISOString().split('T')[0],
    note: 'Shared ride',
  },
  {
    id: 'tx-5',
    type: 'expense',
    desc: 'Grameenphone 30GB Data Pack',
    category: 'recharge',
    amount: 499,
    date: new Date(Date.now() - 86400000).toISOString().split('T')[0],
    note: '30 Days Validity',
  },
  {
    id: 'tx-6',
    type: 'expense',
    desc: 'Nilkhet Course Textbook Print',
    category: 'printout',
    amount: 340,
    date: new Date(Date.now() - 86400000 * 3).toISOString().split('T')[0],
    note: 'CSE 301 PDF binding',
  },
  {
    id: 'tx-7',
    type: 'expense',
    desc: 'Restaurant Treat & Ice Cream',
    category: 'partner',
    amount: 1030,
    date: new Date(Date.now() - 86400000 * 4).toISOString().split('T')[0],
    note: 'Date night dinner bundle',
  },
  {
    id: 'tx-8',
    type: 'expense',
    desc: 'Turf Football Booking Share',
    category: 'sports',
    amount: 300,
    date: new Date(Date.now() - 86400000 * 5).toISOString().split('T')[0],
    note: 'Weekend match with batchmates',
  },
  {
    id: 'tx-9',
    type: 'expense',
    desc: 'Cigarettes & Evening Milk Tea',
    category: 'essentials',
    amount: 115,
    date: new Date().toISOString().split('T')[0],
    note: 'Benson + 2 cups tea',
  },
];
